# Change these first
owner: MGalaCyber # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Portofolio
    url: http://galacyber.is-a.dev
  - name: Universe bot
    url: https://universebot.space
  - name: Universe API
    url: https://api.universebot.space
  - name: CountDown NewYear
    url: https://galacyber.is-a.dev/CountDown-NewYears

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: galacyber.is-a.dev/status
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GalaXd Site Status
  introTitle: "**Status Dashboard** is the place where you can see all my site uptime status."
  introMessage: This status is **real-time**, [Ko-Fi](https://ko-fi.com/galaxd1274) to kept all site online.
  navbar:
    - title: Home
      href: /
    - title: Portofolio
      href: https://galacyber.is-a.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.gg/$OWNER/$REPO
    - title: Ko-Fi
      href: https://ko-fi.com/galaxd1274

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
